[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Katsuki <Katsuki_Sato0130@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
